packages/adapter/src/index.ts
packages/adapter/src/methods.ts
packages/adapter/src/snap.ts
packages/example/src/containers/Dashboard/Dashboard.tsx
packages/example/src/services/metamask.ts
packages/snap/src/asset/index.ts
packages/snap/src/configuration/index.ts
packages/snap/src/configuration/predefined.ts
packages/snap/src/rpc/configure.ts
packages/snap/src/snap.ts
packages/snap/test/unit/rpc/configure.test.ts
packages/types/index.d.ts

- add configure to the adapter
- implement asset management
- refactor Dashboard
- add [asset image](https://svgshare.com/i/M4s.svg) to configurations
Closes #19

Add asset management

---

packages/example/src/components/TransactionTable/TransactionTable.tsx
packages/example/src/containers/Dashboard/Dashboard.tsx
packages/snap/src/filecoin/tx.ts
packages/snap/src/interfaces.ts
packages/snap/src/rpc/getTransactions.ts
packages/snap/src/snap.ts
packages/snap/test/unit/filecoin/tx.test.ts
packages/snap/test/unit/rpc/configure.test.ts
packages/types/index.d.ts

closes #10 
- expand snap state with transactions
- add function for adding and editing transactions in the state
- add transaction table inside Dashboard
- add tests

Expose method for wallet transactions

---

packages/example/src/components/TransactionTable/TransactionTable.tsx
packages/example/src/containers/Dashboard/Dashboard.tsx
packages/example/src/style/theme.ts
packages/snap/package.json
packages/snap/src/configuration/predefined.ts
packages/snap/src/rpc/getBalance.ts
packages/snap/src/snap.ts
packages/snap/src/util/format.ts
packages/snap/test/unit/rpc/getBalance.test.ts
yarn.lock

Multiple minor upgrades:
- fix RPC url
- add `BN.js` to manipulate balances from RPC
- fix transactions table labels
- add example title and change secondary color
- update `snaps-cli` version

First milestone upgrades

---

packages/snap/@types/filecoin-signing-tools/index.d.ts
packages/snap/src/filecoin/account.ts
packages/snap/src/rpc/signMessage.ts
packages/snap/test/unit/rpc/signMessage.test.ts
packages/snap/tsconfig.json

Implement message signing rpc method

---

packages/example/src/components/TransactionTable/TransactionTable.tsx
packages/example/src/components/Transfer/Transfer.tsx
packages/snap/src/configuration/predefined.ts
packages/snap/test/unit/filecoin/account.test.ts

- Fix some naming inside the example
- New devnet configuration

Minor upgrades

---

packages/adapter/src/index.ts
packages/adapter/src/methods.ts
packages/example/src/components/TransactionTable/TransactionTable.tsx
packages/example/src/components/Transfer/Transfer.tsx
packages/snap/src/configuration/predefined.ts
packages/snap/src/filecoin/api.ts
packages/snap/src/filecoin/message.ts
packages/snap/src/rpc/sendMessage.ts
packages/snap/src/rpc/signMessage.ts
packages/snap/test/unit/filecoin/message.test.ts
packages/snap/test/unit/rpc/configure.test.ts
packages/snap/test/unit/rpc/signMessage.test.ts
packages/types/index.d.ts

As described in issue:
- Rename BlockInfo type
- Restructure Message types
- Write basic code documentation (adapter and API methods)
- Refactor balance formating
- Finish predefined configurations
- Define default values for gasprice and gaslimit
- Refactor message status to reflect message CID (not block CID)
closes #39

Code cleanup

---

packages/adapter/src/types.ts
packages/snap/src/asset/index.ts

rename old polkadot names to filecoin

---

packages/adapter/package.json
packages/adapter/src/index.ts
packages/snap/package.json
packages/types/package.json

**filsnap-types**
https://www.npmjs.com/package/@nodefactory/filsnap-types
**filsnap-adapter**
https://www.npmjs.com/package/@nodefactory/filsnap-adapter
**filsnap**
https://www.npmjs.com/package/@nodefactory/filsnap

Release 0.2.1

---

packages/snap/@types/filecoin-signing-tools/index.d.ts
packages/snap/package.json
packages/snap/src/configuration/predefined.ts
packages/snap/src/filecoin/account.ts
packages/snap/test/unit/filecoin/account.test.ts
packages/snap/test/unit/rpc/exportSeed.test.ts
packages/snap/test/unit/rpc/getAdress.test.ts
packages/snap/test/unit/rpc/getBalance.test.ts
packages/snap/test/unit/rpc/getPublicKey.test.ts
packages/snap/test/unit/rpc/keyPairTestConstants.ts
packages/snap/test/unit/rpc/signMessage.test.ts
packages/snap/tsconfig.json
yarn.lock

blocked by relevant permissions added to metamask-snaps-beta https://github.com/MetaMask/metamask-snaps-beta/pull/166

snap - add permission for getting key material by bip44 code

---

packages/snap/src/asset/index.ts

- fix block explorer URL for asset custom view
fixes #69

Fix filscan asset url

---

packages/adapter/package.json
packages/adapter/src/index.ts
packages/snap/package.json
packages/types/package.json

#74 
#73 
- [filsnap-types](https://www.npmjs.com/package/@nodefactory/filsnap-types?activeTab=readme)
- [filsnap](https://www.npmjs.com/package/@nodefactory/filsnap)
- [filsnap-adapter](https://www.npmjs.com/package/@nodefactory/filsnap-adapter)
- [package.json](https://bafybeigzphbumdkucnj2c6nr5xb3kwsq5gs2gp7w3qldgbvfeycfsbjylu.ipfs.infura-ipfs.io/)
- [bundle.js](https://bafybeiaheao44qciej35juo3oqcbtb4afk6yxhvwt7s4zeszdfqbearf5u.ipfs.infura-ipfs.io/)

Publish version v1.0.0 of packages

---

packages/snap/src/rpc/signMessage.ts
packages/snap/test/unit/rpc/signMessage.test.ts
packages/types/index.d.ts

Allow nonce override

---

packages/snap/src/filecoin/account.ts
packages/snap/test/unit/rpc/getAdress.test.ts

Fix account derivation to respect all derivation path fields

---

packages/adapter/src/index.ts

add isSnapInstalled export

---

packages/adapter/src/methods.ts
packages/example/src/components/Transfer/Transfer.tsx
packages/snap/@types/filecoin-number/index.d.ts
packages/snap/package.json
packages/snap/snap.manifest.json
packages/snap/src/rpc/estimateMessageGas.ts
packages/snap/src/snap.ts
packages/types/index.d.ts
yarn.lock

I tried to use [@glif/filecoin-number](https://www.npmjs.com/package/@glif/filecoin-number) instead of [@openworklabs/filecoin-number](https://www.npmjs.com/package/@openworklabs/filecoin-number) but ses evaluation fails, so I will move it to separate issue.
Closes #94

Set max fee

---

packages/adapter/src/index.ts

Export MetamaskFilecoinSnap class

---

packages/snap/src/rpc/signMessage.ts
packages/snap/test/unit/rpc/signMessage.test.ts
packages/types/index.d.ts

SingMessage params

---

packages/example/src/components/Transfer/Transfer.tsx
packages/example/src/services/utils.ts

fix: transfer panel format changed to FIL

---

packages/snap/snap.manifest.json
packages/snap/src/rpc/signMessage.ts
packages/snap/src/util/messageCreator.ts
packages/types/index.d.ts

fix: singMessage missing method parameter

---

packages/snap/package.json
packages/snap/snap.manifest.json
packages/snap/src/rpc/signMessage.ts
yarn.lock

Fix https://github.com/ChainSafe/filsnap/issues/143
Fix https://github.com/ChainSafe/filsnap/issues/144

fix: message approval UI

---

packages/snap/@types/lotus-client-provider-nodejs/index.d.ts
packages/snap/package.json
packages/snap/snap.manifest.json
packages/snap/src/filecoin/api.ts
yarn.lock

fix: change content type for filecoin rpc to json

---

packages/example/src/containers/MetaMaskConnector/MetaMaskConnector.tsx
yarn.lock

Resolves UI issue reported over a slack

fix: missing flask warning

---

packages/adapter/src/index.ts

changed default origin from `ipfs` to `npm`

fix: default origin

---

.release-please-manifest.json
packages/adapter/CHANGELOG.md
packages/adapter/package.json
packages/snap/CHANGELOG.md
packages/snap/package.json
packages/snap/snap.manifest.json

chore: Revert "chore: release master"
